(function(){function not_found(it
/**/) {
var out='<!DOCTYPE html><html><head><meta charset="utf-8"><title>'+(it.site.name)+'</title><meta http-equiv="x-dns-prefetch-control" content="on"><link rel="dns-prefetch" href="//'+(it.site.url)+'" /><link rel="dns-prefetch" href="//www.google-analytics.com" /><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="description" content="'+(it.site.description)+'"><meta name="keywords" content="'+(it.site.description)+'"><meta name="robots" content="index,follow"><!-- Open Graph Protocol --><meta property="og:site_name" content="'+(it.site.name)+'"><meta property="og:url" content="//'+(it.url)+'"><meta property="og:title" content="'+(it.title)+'"><!-- Google+ Snippets --><meta itemprop="url" content="//'+(it.url)+'"><meta itemprop="name" content="'+(it.site.name)+'"><link rel="icon" href="/favicon.ico" type="image/x-icon"><link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"><link rel="stylesheet" href="/assets/style/font.css" type="text/css" /><link rel="stylesheet" href="/assets/style/default.css" type="text/css" /><link rel="stylesheet" href="/assets/style/card.css" type="text/css" /><link rel="stylesheet" href="/assets/style/form.css" type="text/css" /><link rel="stylesheet" href="/assets/style/buttons.css" type="text/css" /><link rel="stylesheet" href="/assets/style/loading.css" type="text/css" /><link rel="stylesheet" href="/assets/style/loading-btn.css" type="text/css" /><link rel="stylesheet" href="/assets/style/footer.css" type="text/css" /><link rel="stylesheet" href="/assets/style/header.css" type="text/css" /><link rel="stylesheet" href="/assets/style/blog.css" type="text/css" /><link rel="stylesheet" href="/assets/style/prism.css" type="text/css" /><link rel="stylesheet" href="/assets/style/normalize.min.css" type="text/css"><link rel="stylesheet" href="/assets/style/basscss.min.css" type="text/css" /></head><body><div class="page-wrap"><header class="mx-auto"><div class="navbar" role="navigation"><a class="navbar-brand" href="//'+(it.site.url)+'">'+(it.site.name)+'</a><hr class="mobile-hr"/><div class="navbar-menu"><ul class="list-reset"><li><a href="/tags">Tags</a></li></ul></div></div></header><div class="container"><div class="max-width-3 mx-auto"><h1 style="text-align: center;">Not Found!</h1></div></div></div><footer class="fit"><div class="poweredby">Powered by <a href="//danielsunami.github.io/neeka">Neeka</a></div></footer><script type="text/javascript" src="/assets/lib/prism.js"></script></body></html>';return out;
}var itself=not_found, _encodeHTML=(function (doNotSkipEncoded) {
		var encodeHTMLRules = { "&": "&#38;", "<": "&#60;", ">": "&#62;", '"': "&#34;", "'": "&#39;", "/": "&#47;" },
			matchHTML = doNotSkipEncoded ? /[&<>"'\/]/g : /&(?!#?\w+;)|<|>|"|'|\//g;
		return function(code) {
			return code ? code.toString().replace(matchHTML, function(m) {return encodeHTMLRules[m] || m;}) : "";
		};
	}());if(typeof module!=='undefined' && module.exports) module.exports=itself;else if(typeof define==='function')define(function(){return itself;});else {_page.render=_page.render||{};_page.render['not_found']=itself;}}());